<a href="https://colab.research.google.com/github/bennyb-bio/Group-A-Project/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import sqlite3
import pandas as pd
import os

# Google Drive mounten
from google.colab import drive
drive.mount("/content/drive")

# Verzeichnis mit den CSV-Dateien
material_path = "/content/drive/MyDrive/Gruppe A/COVID 19 data"
!ls "{material_path}"

# Name der SQLite-Datenbank
database_file = "covid19_data.db"

try:
    # Verbindung zur SQLite-Datenbank herstellen
    conn = sqlite3.connect(database_file)
    cursor = conn.cursor()

    # Fremdschlüssel aktivieren
    cursor.execute("PRAGMA foreign_keys = ON;")

    # Tabellen erstellen und Daten importieren
    table_creation_queries = {
        "observations": """
            CREATE TABLE IF NOT EXISTS observations (
                DATE TEXT,
                PATIENT TEXT,
                ENCOUNTER TEXT,
                CODE TEXT,
                DESCRIPTION TEXT,
                VALUE TEXT,
                UNITS TEXT,
                TYPE TEXT,
                FOREIGN KEY (PATIENT)
                  REFERENCES patients (Id)
            );
        """,
        "patients": """
            CREATE TABLE IF NOT EXISTS patients (
                Id TEXT PRIMARY KEY,
                BIRTHDATE TEXT,
                DEATHDATE TEXT,
                SSN TEXT,
                DRIVERS TEXT,
                PASSPORT TEXT,
                PREFIX TEXT,
                FIRST TEXT,
                LAST TEXT,
                SUFFIX TEXT,
                MAIDEN TEXT,
                MARITAL TEXT,
                RACE TEXT,
                ETHNICITY TEXT,
                GENDER TEXT,
                BIRTHPLACE TEXT,
                ADDRESS TEXT,
                CITY TEXT,
                STATE TEXT,
                COUNTRY TEXT,
                ZIP TEXT,
                LAT REAL,
                LON REAL,
                HEALTHCARE_EXPENSES REAL,
                HEALTHCARE_COVERAGE REAL
            );
        """,
        "conditions": """
            CREATE TABLE IF NOT EXISTS conditions (
                START TEXT,
                STOP TEXT,
                PATIENT TEXT,
                ENCOUNTER TEXT,
                CODE TEXT,
                DESCRIPTION TEXT,
                FOREIGN KEY (PATIENT)
                  REFERENCES patients (Id)
            );
        """
    }

    csv_files = {
        f"{material_path}/observations.csv": "observations",
        f"{material_path}/patients.csv": "patients",
        f"{material_path}/conditions.csv": "conditions"
    }

    for csv_file, table_name in csv_files.items():
        # Tabelle erstellen
        try:
            print(f"Erstelle Tabelle: {table_name}")
            cursor.execute(table_creation_queries[table_name])
            conn.commit()
        except Exception as e:
            print(f"[FEHLER] Tabelle '{table_name}' konnte nicht erstellt werden: {e}")
            continue

        # CSV-Datei prüfen und Daten importieren
        if not os.path.exists(csv_file):
            print(f"[WARNUNG] Die Datei {csv_file} existiert nicht.")
            continue

        try:
            df = pd.read_csv(csv_file)
            print(f"Importiere Daten in die Tabelle {table_name}...")
            df.to_sql(table_name, conn, if_exists="replace", index=False)
        except Exception as e:
            print(f"[FEHLER] Import in Tabelle '{table_name}' fehlgeschlagen: {e}")

    print(f"Die Daten wurden erfolgreich in die Datenbank '{database_file}' importiert.")

except Exception as e:
    print(f"Ein Fehler ist aufgetreten: {e}")

finally:
    if conn:
        print("Schließe die Datenbankverbindung.")
        conn.close()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
careplans.csv	 devices.csv	  imaging_studies.csv	observations.csv   payers.csv
careplans.xlsx	 disease.csv	  imaging_studies.xlsx	observations.xlsx  payer_transitions.csv
conditions.csv	 disease.xlsx	  immunizations.csv	organizations.csv  procedures.csv
conditions.xlsx  encounters.csv   medications.csv	patients.csv	   providers.csv
covid19_test.db  encounters.xlsx  medications.xlsx	patients.xlsx	   supplies.csv
Erstelle Tabelle: observations
Importiere Daten in die Tabelle observations...
Erstelle Tabelle: patients
Importiere Daten in die Tabelle patients...
Erstelle Tabelle: conditions
Importiere Daten in die Tabelle conditions...
Die Daten wurden erfolgreich in die Datenbank 'covid19_data.db' importiert.
Schließe die Datenbankverbindung.

In [5]:
import sqlite3
import pandas as pd

def reopen_and_inspect_database(db_file):
    """
    Öffnet die Verbindung zu einer SQLite-Datenbank, listet die vorhandenen Tabellen
    und zeigt die ersten Zeilen (max. 5) jeder Tabelle an.
    """
    try:
        # Verbindung zur Datenbank herstellen
        conn = sqlite3.connect(db_file)
        cursor = conn.cursor()

        # Tabellen abfragen
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = cursor.fetchall()

        if not tables:
            print("Die Datenbank enthält keine Tabellen.")
            return

        print(f"Tabellen in der Datenbank '{db_file}':")
        for table in tables:
            table_name = table[0]
            print(f"\nTabelle: {table_name}")

            # Inhalte der Tabelle abfragen
            query = f"SELECT * FROM {table_name} LIMIT 5;"  # Zeigt die ersten 5 Zeilen an
            try:
                df = pd.read_sql_query(query, conn)
                if df.empty:
                    print(f"Die Tabelle '{table_name}' ist leer.")
                else:
                    print(f"Inhalt der Tabelle '{table_name}':")
                    print(df)
            except Exception as e:
                print(f"Fehler beim Abrufen der Daten aus der Tabelle '{table_name}': {e}")

    except sqlite3.Error as e:
        print(f"Fehler beim Zugriff auf die Datenbank: {e}")
    finally:
        if conn:
            conn.close()
            print("Datenbankverbindung geschlossen.")

# Name der SQLite-Datenbank
database_file = "covid19_data.db"

# Funktion ausführen
reopen_and_inspect_database(database_file)

Tabellen in der Datenbank 'covid19_data.db':

Tabelle: observations
Inhalt der Tabelle 'observations':
                   DATE                               PATIENT  \
0  2020-02-17T21:57:21Z  ad5525c0-fdab-94dc-018f-d7209c72bdef
1  2020-02-17T21:57:21Z  ad5525c0-fdab-94dc-018f-d7209c72bdef
2  2020-02-17T21:57:21Z  ad5525c0-fdab-94dc-018f-d7209c72bdef
3  2020-02-17T21:57:21Z  ad5525c0-fdab-94dc-018f-d7209c72bdef
4  2020-02-17T21:57:21Z  ad5525c0-fdab-94dc-018f-d7209c72bdef

                              ENCOUNTER    CODE  \
0  1d453a83-17f7-490d-5576-09f5725cdcaa  8310-5
1  1d453a83-17f7-490d-5576-09f5725cdcaa  9279-1
2  1d453a83-17f7-490d-5576-09f5725cdcaa  8867-4
3  1d453a83-17f7-490d-5576-09f5725cdcaa  2708-6
4  1d453a83-17f7-490d-5576-09f5725cdcaa  8462-4

                           DESCRIPTION VALUE   UNITS     TYPE
0                     Body temperature  41.4     Cel  numeric
1                     Respiratory rate  21.4    /min  numeric
2                           Heart rate  61.6    /min  numeric
3  Oxygen saturation in Arterial blood  77.4       %  numeric
4             Diastolic Blood Pressure  85.0  mm[Hg]  numeric

Tabelle: patients
Inhalt der Tabelle 'patients':
                                     Id   BIRTHDATE DEATHDATE          SSN  \
0  2f114e21-8b95-e9eb-2e9e-4b950b059cfa  2002-05-05      None  999-23-8106
1  2812f4fc-6aba-0033-728b-7e569bb8adcc  1942-05-24      None  999-24-5281
2  9b1a203a-6368-49a5-0c79-45c32729bc17  2013-06-15      None  999-75-9525
3  52a250a9-24e4-ec9b-91d6-c38cf1b10fc0  1997-11-16      None  999-26-4891
4  ad5525c0-fdab-94dc-018f-d7209c72bdef  1965-08-28      None  999-29-9941

     DRIVERS    PASSPORT PREFIX      FIRST         LAST SUFFIX  ...  \
0  S99926648        None    Ms.  Terisa250   Kreiger457   None  ...
1  S99910925  X76697172X    Mr.   Romeo514     Morar593   None  ...
2       None        None   None   Jamaal34     Hessel84   None  ...
3  S99979802  X57430890X    Ms.   Kenya524  Leuschke194   None  ...
4  S99959414  X19338033X    Mr.   Clark193    Little434   None  ...

                       BIRTHPLACE                        ADDRESS        CITY  \
0       Oxford  Massachusetts  US         325 Robel Route Apt 85  Swampscott
1  Springfield  Massachusetts  US         496 Klein Wynd Unit 85    Charlton
2   Framingham  Massachusetts  US              184 Corkery Byway     Methuen
3       Easton  Massachusetts  US  634 Predovic Mission Suite 14    Yarmouth
4       Lowell  Massachusetts  US              950 Kshlerin Park      Malden

           STATE             COUNTY     ZIP        LAT        LON  \
0  Massachusetts       Essex County  1907.0  42.472736 -70.876528
1  Massachusetts   Worcester County     NaN  42.131465 -71.970333
2  Massachusetts       Essex County     NaN  42.730660 -71.159442
3  Massachusetts  Barnstable County     NaN  41.663563 -70.234152
4  Massachusetts   Middlesex County  2148.0  42.392584 -71.078063

  HEALTHCARE_EXPENSES HEALTHCARE_COVERAGE
0           471180.00             2784.81
1          1606235.00             5375.37
2           172970.00             2074.05
3           557170.00             2653.13
4            68024.89             2743.96

[5 rows x 25 columns]

Tabelle: conditions
Inhalt der Tabelle 'conditions':
        START        STOP                               PATIENT  \
0  2020-02-17  2020-02-27  ad5525c0-fdab-94dc-018f-d7209c72bdef
1  2020-02-24  2020-03-11  7f30313f-98e9-2cc2-68a5-6f9973f9ad5a
2  2020-02-17  2020-02-27  ad5525c0-fdab-94dc-018f-d7209c72bdef
3  2020-02-17  2020-02-27  ad5525c0-fdab-94dc-018f-d7209c72bdef
4  2020-02-17  2020-02-17  ad5525c0-fdab-94dc-018f-d7209c72bdef

                              ENCOUNTER       CODE              DESCRIPTION
0  1d453a83-17f7-490d-5576-09f5725cdcaa   49727002          Cough (finding)
1  ccb50c60-5c51-3d03-3aeb-824325cfac91   49727002          Cough (finding)
2  1d453a83-17f7-490d-5576-09f5725cdcaa  386661006          Fever (finding)
3  1d453a83-17f7-490d-5576-09f5725cdcaa   36955009  Loss of taste (finding)
4  1d453a83-17f7-490d-5576-09f5725cdcaa  840544004       Suspected COVID-19
Datenbankverbindung geschlossen.